pybullet:
  simulation:
    gravity: [0, 0, -9.81]
    time_step: 0.016666666666666666
    num_solver_iterations: 5
    num_substeps: 4
  robot:
    urdf_path: "/urdf/tt.urdf"
    start_position: [0, 0, 0.3]
    start_orientation: [1.5707963267948966, 0, -3.1415926535897932]
    power: 16 #Watt 
task:
  goal_radius: 5
  goal_angle_bounds: [-45, 45]
  smoothing_factor: 0.9
  distance_threshold: 0.1
  fall_threshold: 0.4
  fall_reward: -100
  forward_velocity_bias: 0.8
  pitch_bias: 20
  max_angle_dip: 10
standing_task:
  time_emphasis: 4.0
  time_threshold: 10.0
  plane_angle_bounds: 15 # +/- 5 degrees
  max_angle_dip: 25
  desired_position: [0, 0, 0.26]
  good_position_reward: 20.0
  distance_threshold: 0.05
stability_policy:
  Kp: 1.0
  Kd: 0.01
stability_metric:
  z_position_emphasis: 10.0
  pitch_emphasis: 10.0
target_policy:
  Kp: 1.0
  Kd: 0.01
target_metric:
  force_x_emphasis: 10.0  
  force_y_emphasis: 10.0